#!/bin/bash

NEW_ROLE=$1

echo "Current role"
aws sts get-caller-identity
echo "Switching to role: $NEW_ROLE"
eval $(aws sts assume-role --role-arn $NEW_ROLE --role-session-name AssumedRole | jq -r '.Credentials | "export AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey)\nexport AWS_SESSION_TOKEN=\(.SessionToken)\nexport AWS_SECURITY_TOKEN=\n"')
echo "New role"
aws sts get-caller-identity